plugins {
	id 'net.fabricmc.fabric-loom' version '1.17.+'
}

apply from: 'https://raw.githubusercontent.com/TerraformersMC/GradleScripts/3.2/ferry.gradle'

loom {
	accessWidenerPath = file("src/main/resources/vistas.accesswidener")
}

dependencies {
	minecraft "com.mojang:minecraft:$project.minecraft_version"

	implementation("net.fabricmc:fabric-loader:$project.loader_version")
	implementation("net.fabricmc.fabric-api:fabric-api:$project.fabric_version")

	implementation("com.terraformersmc:modmenu:$project.modmenu_version")
	include(implementation("me.shedaniel.cloth:cloth-config-fabric:${project.clothconfig_version}"))
}

repositories {
	maven {
		url = 'https://jitpack.io'
	}
	maven {
		url = 'https://maven.terraformersmc.com/'
	}
	maven {
		url = 'https://maven.shedaniel.me/'
	}
}

jar {
	from("MPL-SOFTWARE-UTILIZED")
}